<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-main.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 وەڵام',
		'1_comment' => '1 سەرنج',
		'1_day' => '1 ڕۆژ',
		'1_disliked' => '1 نەخوازراو',
		'1_flag' => '1 نیشانە',
		'1_hour' => '1 کاتژمێر',
		'1_liked' => '1 خوازراو',
		'1_minute' => '1 خولەک',
		'1_month' => '1 مانگ',
		'1_point' => '1 خاڵ',
		'1_question' => '1 پرسیار',
		'1_second' => '1 چرکە',
		'1_tag' => '1 تاگ',
		'1_user' => '1 بەکارهێنەر',
		'1_view' => '1 بینین',
		'1_vote' => '1 دەنگ',
		'1_week' => '1 هەفتە',
		'1_year' => '1 ساڵ',
		'add_category_x_favorites' => 'زیادکردنی هاوپۆلی ^ بۆ ناو دڵخوازەکانم',
		'add_favorites' => 'زیادکردن بۆ ناو دڵخوازەکانم',
		'add_tag_x_favorites' => 'زیادکردنی تاگ ^ بۆ ناو دڵخوازەکانم',
		'all_categories' => 'هەموو هاوپۆلەکان',
		'anonymous' => 'نەناسراو',
		'answer_edited' => 'وەڵام دەستکاریکرا',
		'answer_reshown' => 'وەڵام دووبارە پیشاندرایەوە',
		'answer_selected' => 'پرسیار دیاری کرا',
		'answered_qs_in_x' => 'زۆرترین پرسیارە وەڵامدراوەکان لە ^',
		'answered_qs_title' => 'زۆرترین پرسیارە وەڵامدراوەکان',
		'answered' => 'وەڵامدرایەوە',
		'asked_related_q' => 'پرسیاری پەیوەندیدار کرا',
		'asked' => 'کراو',
		'by_x' => 'لەلایەن ^',
		'cancel_button' => 'هەڵوەشاندنەوە',
		'closed' => 'داخرا',
		'comment_edited' => 'سەرنج دەستکاریکرا',
		'comment_moved' => 'سەرنج جوڵیندرا',
		'comment_reshown' => 'سەرنجی دووبارە پیشاندراو',
		'commented' => 'سەرنجدراو',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^month ^day, ^year',
		'date_format_this_year' => '^month ^day',
		'date_month_1' => 'کانونی دووەم',
		'date_month_2' => 'شوبات',
		'date_month_3' => 'ئادار',
		'date_month_4' => 'نیسان',
		'date_month_5' => 'ئایار',
		'date_month_6' => 'حوزەیران',
		'date_month_7' => 'تەمموز',
		'date_month_8' => 'ئاب',
		'date_month_9' => 'ئەیلول',
		'date_month_10' => 'تشرینی یەکەم',
		'date_month_11' => 'تشرینی دووەم',
		'date_month_12' => 'کانونی یەکەم',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'دەستکاریکراو',
		'field_required' => 'بەیارمەتیت شتێک لەم بۆشاییە بنوسە',
		'general_error' => '.هەڵەیەکی سێرڤەر هاتەپێش - بەیارمەتیت دوبارە هەوڵبدەرەوە',
		'hidden' => 'شاردرایەوە',
		'highest_users' => 'باشترین بەکارهێنەرە خاڵ تۆمارکەرەکان',
		'hot_qs_in_x' => 'پرسیارە گەرماو گەرمەکان لە ^',
		'hot_qs_title' => 'پرسیارە گەرماو گەرمەکان',
		'image_not_read' => ':ناتوانرێت وێنەکە بخوێندرێتەوە. بەیارمەتیت یەکێک لەمانە ^',
		'image_too_big_x_pc' => '.ئەم وێنەیە زۆر گەورەیە. بە یارمەتیت پێوانەی بکە بۆ ^% پاشان هەوڵ بدەرەوە',
		'in_category_x' => 'لە ^',
		'ip_address_x' => 'ناونیشانی ئای پی ^',
		'logged_in_x' => 'سڵاو ^',
		'max_length_x' => 'بەرزترین ڕێژەی درێژی بریتییە لە ^ پیت',
		'me' => 'من',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'بەیارمەتیت زانیاری زیاتر بدە - بە لایەنی کەمەوە ^ پیت',
		'max_upload_size_x' => 'بەرزترین قەبارەی ئەپڵۆدکردن بریتییە لە ^',
		'moved' => 'جوڵێندرا',
		'nav_account' => 'هەژمارەکەم',
		'nav_activity' => 'هەموو چالاکییەکان',
		'nav_admin' => 'بەڕێوەبەر',
		'nav_ask' => 'پرسیارێک بکە',
		'nav_categories' => 'هاوپۆلەکان',
		'nav_feedback' => 'ناردنی سەرنج و پێشنیار',
		'nav_home' => 'ماڵەوە',
		'nav_hot' => 'گەرماوگەرم',
		'nav_login' => 'چونە ژوورەوە',
		'nav_logout' => 'چونە دەرەوە',
		'nav_most_answers' => 'زۆرترین وەڵامەکان',
		'nav_most_recent' => 'نوێترین',
		'nav_most_views' => 'زۆرترین بینراوەکان',
		'nav_most_votes' => 'زۆرترین دەنگەکان',
		'nav_no_answer' => 'بێ وەڵام',
		'nav_no_selected_answer' => 'نەبوونی وەڵامی دیاریکراو',
		'nav_no_upvoted_answer' => 'نەبوونی وەڵامی بەڵێ',
		'nav_qa' => 'پرسیار&وەڵام',
		'nav_qs' => 'پرسیارەکان',
		'nav_register' => 'تۆماربوون',
		'nav_tags' => 'تاگەکان',
		'nav_unanswered' => 'وەڵام نەدراوەکان',
		'nav_updates' => 'بەڕۆژکراوەکانم',
		'nav_users' => 'بەکارهێنەران',
		'no_active_users' => 'هیچ بەکارهێنەرێکی چالاک نەدۆزرایەوە',
		'no_answers_found' => 'هیچ وەڵامێک نەدۆزرایەوە',
		'no_answers_in_x' => 'نەبوونی وەڵامەکان لە ^',
		'no_categories_found' => 'هیچ هاوپۆلێک نەدۆزرایەوە',
		'no_category' => 'نەبوونی هاوپۆل',
		'no_comments_found' => 'هیچ سەرنجێک نەدۆزرایەوە',
		'no_comments_in_x' => 'نەبوونی سەرنجەکان لە ^',
		'no_questions_found' => 'هیچ پرسیارێک نەدۆزرایەوە',
		'no_questions_in_x' => 'نەبوونی پرسیار لە ^',
		'no_related_qs_title' => 'هیچ پرسیارێک پەیوەندی دار نەدۆزرایەوە',
		'no_results_for_x' => 'هیچ ئەنجامێک نەدۆزرایەوە بۆ ^',
		'no_tags_found' => 'هیچ تاگێک نەدۆزرایەوە',
		'no_una_questions_found' => 'هیچ پرسیارێکی وەڵام نەدراوە نەدۆزرایەوە',
		'no_una_questions_in_x' => 'هیچ پرسیارێکی وەڵام نەدراوە لە ^',
		'no_unselected_qs_found' => 'هیچ پرسیارێک نەدۆزرایەوە بەبێ وەڵامێکی دیاریکراو',
		'no_unupvoteda_qs_found' => 'هیچ پرسیارێک نەدۆزرایەوە بەبێ وەڵامێکی بەڵێ',
		'page_label' => ':پەڕ',
		'page_next' => 'دواتر',
		'page_not_found' => 'پەڕەکە نەدۆزرایەوە',
		'page_prev' => 'پێشتر',
		'popular_tags' => 'دیارترین تاگەکان',
		'questions_tagged_x' => 'نوێترین پرسیارە تاگکراوەکان ^',
		'recategorized' => 'دوبارە هاوپۆلکراو',
		'recent_activity_in_x' => 'نوێترین چالاکی لە ^',
		'recent_activity_title' => 'نوێترین چالاکی',
		'recent_as_in_x' => 'نوێترین پرسیارە وەڵامدراوەکان لە ^',
		'recent_as_title' => 'نوێترین پرسیارە وەڵام دراوەکان',
		'recent_cs_in_x' => 'نوێترین سەرنجە زیادکراوەکان لە ^',
		'recent_cs_title' => 'نوێترین سەرنجە زیادکراوەکان',
		'recent_qs_as_in_x' => 'نوێترین پرسیار و وەڵامەکان لە ^',
		'recent_qs_as_title' => 'نوێترین پرسیار و وەڵامەکان',
		'recent_qs_in_x' => 'نوێترین پرسیارەکان لە ^',
		'recent_qs_title' => 'نوێترین پرسیارەکان',
		'related_qs_title' => 'پرسیارە پەیوەندیدارەکان',
		'remove_favorites' => 'بیسڕەوە لە دڵخوازەکانم',
		'remove_x_favorites' => 'بیسڕەوە  ^ لە دڵخوازەکانم',
		'reopened' => 'دوبارەکردراوە',
		'reshown' => 'دوبارە پیشاندراو',
		'results_for_x' => 'ئەنجامی گەڕانەکان بۆ ^',
		'retagged' => 'دوبارەتاگکراو',
		'save_button' => 'پاشەکەوتکردنی گۆڕانکارییەکان',
		'search_button' => 'گەڕان',
		'search_explanation' => '.بە یارمەتیت هەندێک نوسین لەناو بۆشای گەڕانەکە بنوسە و دوبارە هەوڵ بدەرەوە',
		'search_title' => 'ئەنجامی گەڕانەکان',
		'selected' => 'دیاریکراو',
		'send_button' => 'ناردن',
		'suggest_ask' => 'هاریکاربە لە دەستپێکردنی شتەکان بە ^1پرسیارکردنێک^2.',
		'suggest_category_qs' => 'بۆ بینینی زیاتر, کرتە بکە بۆ هەموو  ^1پرسیارەکان لەم هاوپۆلەدا^2.',
		'suggest_qs_tags' => 'بۆ بینینی زیاتر, کرتە بکە بۆ  ^1لیستی تەواوی پرسیارەکان^2 یان ^3تاگە دیارەکان^4.',
		'suggest_qs' => 'بۆ بینینی زیاتر, کرتە بکە بۆ  ^1لیستی تەواوی پرسیارەکان^2.',
		'unanswered_qs_in_x' => ':پرسیارە بێ وەڵامەکان لە ^',
		'unanswered_qs_title' => 'نوێترین پرسیارە بێ وەڵامەکان',
		'unselected_qs_in_x' => ':پرسیارەکان بەبێ وەڵامێکی دیاریکراو لە ^',
		'unselected_qs_title' => 'نوێترین پرسیارەکان بەبێ وەڵامێکی دیاریکراو',
		'unupvoteda_qs_in_x' => ':پرسیارەکان بەبێ وەڵامی دەنگی بەڵێ لە ^',
		'unupvoteda_qs_title' => 'نوێترین پرسیارەکان بەبێ وەڵامی دەنگی بەڵێ',
		'upload_limit' => 'ئەپلۆدی زۆرکراوە - بەیارمەتیت کاتژمێرێکی تر هەوڵ بدەرەوە',
		'view_q_must_confirm' => 'بەیارمەتیت ^5دوپاتی ئیمەیڵەکەت بکەرەوە^6  بۆ بینینی پەڕی پرسیارەکان.',
		'view_q_must_login' => 'بەیارمەتیت ^1بچۆرە ژورەوە^2 یان ^3خۆت تۆماربکە^4 بۆ بینینی پەڕی پرسیارەکان.',
		'viewed_qs_in_x' => 'زۆرترین پرسیارە بینراوەکان لە ^',
		'viewed_qs_title' => 'زۆرترین پرسیارە بینراوەکان',
		'vote_disabled_down' => 'دەنگدانی نەخێر تەنها بۆ هەندێک لە بەکارهێنەران بەردەستە',
		'vote_disabled_hidden_a' => 'تۆ ناتوانیت لەسەر وەڵامە شاردراوەکان دەنگ بدەیت',
		'vote_disabled_hidden_q' => 'تۆ ناتوانیت لەسەر پرسیارە شاردراوەکان دەنگ بدەیت',
		'vote_disabled_level' => 'دەنگدان تەنها بۆ هەندێک لە بەکارهێنەران بەردەستە',
		'vote_disabled_my_a' => 'تۆ ناتوانیت لەسەر وەڵامەکانی خۆت دەنگ بدەیت',
		'vote_disabled_my_q' => 'تۆ ناتوانیت لەسەر پرسیارەکانی خۆت دەنگ بدەیت',
		'vote_disabled_q_page_only' => 'بە یارمەتیت ئەم پرسیارە پیشان بدە بۆ دەنگدان',
		'vote_down_must_confirm' => 'بەیارمەتیت ^5دوپاتی ئیمەیڵەکەت بکەوە^6 بۆ دەنگدان بە نەخێر.',
		'vote_down_popup' => 'کرتە بکە بۆ دەنگدان بە نەخێر',
		'vote_limit' => 'دەنگی زۆر وەرگیراوە - بەیارمەتیت دوای کاتژمێرێکی تر هەوڵ بدەرەوە',
		'vote_must_confirm' => 'بەیارمەتیت ^5دوپاتی ئیمەیڵەکەت بکەوە^6 بۆ دەنگدان.',
		'vote_must_login' => 'بەیارمەتیت ^1بچۆرە ژورەوە^2 یان  ^3خۆت تۆماربکە ^4 بۆ دەنگدان.',
		'vote_not_allowed' => 'دەنگدان لەسەر ئەمە ڕێگە پێدراو نیە',
		'vote_up_popup' => 'کرتە بکە بۆ دەنگدان بە بەڵێ',
		'voted_down_popup' => 'تۆ دەنگی نەخێرت بە ئەمە داوە - کرتە بکە بۆ سڕینەوەی دەنگ',
		'voted_qs_in_x' => 'بەرزترین پرسیاری دەنگ پێدراو لە ^',
		'voted_qs_title' => 'بەرزترین پرسیارە دەنگ پێدراوەکان',
		'voted_up_popup' => 'تۆ دەنگی بەڵێت بە ئەمە داوە - کرتە بکە بۆ سڕینەوەی دەنگ',
		'x_ago' => '^ لەمەوبەر',
		'x_answers' => '^ وەڵام',
		'x_comments' => '^ سەرنج',
		'x_days' => '^ ڕۆژ',
		'x_disliked' => '^ نەخوازراو',
		'x_flags' => '^ نیشانەکراو',
		'x_hours' => '^ کاتژمێر',
		'x_liked' => '^ خوازراو',
		'x_minutes' => '^ خولەک',
		'x_months' => '^ مانگ',
		'x_points' => '^ خاڵ',
		'x_questions' => '^ پرسیار',
		'x_seconds' => '^ چرکە',
		'x_tags' => '^ تاگ',
		'x_users' => '^ بەکارهێنەر',
		'x_views' => '^ بینراو',
		'x_votes' => '^ دەنگ',
		'x_weeks' => '^ هەفتە',
		'x_years' => '^ ساڵ',
		'email_error' => "هەڵەیەک هاتەپێش لەکاتی هەوڵدان بۆ ناردنی ئیمەیڵەکە.",
		'file_upload_limit_exceeded' => "قەبارەی فایلەکە لە سنوری قەبارەی سێرڤەر تێپەڕی کرد",
		'since_x' => "لەوەتەی ^",
		'to_x' => "بۆ ^",
		'view_q_must_be_approved' => "هەژمارەکەت پێویستە دانی پێدابنرێت بۆ بینینی پەڕی پرسیارەکان.",
		'vote_disabled_approve' => "هەژمارەکەت پێویستە دانی پێدابنرێت پێش ئەوەی بتوانیت دەنگ بدەیت.",
		'vote_disabled_down_approve' => "هەژمارەکەت پێویستە دانی پێدابنرێت پێش ئەوەی دەنگ بە نەخێر بدەیت",
		'written' => "",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/